#!/usr/bin/env bash
#script para instalar nginx
#sobrescribir lo anterior del arcchivo:
#por 'hello world'
#Y volver a iniciar el servidor
sudo apt update
sudo apt -y install nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
