#!/usr/bin/env bash
# Configurar servidor Nginx para que /redirect_me rediriga a otra página
# sed -> 
# tee ->
sudo echo "Hello World" | sudo tee /var/www/html/index.html > /dev/null
sudo sed -i '/server_name _;/a rewrite ^/redirect_me/ https://www.google.com permanent;' /etc/nginx/sites-available/default
sudo service nginx restart