#!/usr/bin/env bash
# Configurar servidor Nginx para que /redirect_me rediriga a otra página
# sed -> remplaza lineas
# tee -> añade sin sobrescribir
sudo apt update
sudo apt -y install nginx
echo "Hello World" > /var/www/html/index.html
sudo sed -i '/server_name _;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default


echo "Ceci n'est pas une page" > /var/www/html/error_page.html
sudo sed -i "/server_name _;/a error_page 404 /error.page.html;\nlocation = /error_page.html}" /etc/nginx/sites-available/default
sudo service nginx restart
