#!/usr/bin/env bash

#los primeros scripts deben ser para que los servidores sean identicos
# - instalar nginx y luego modificar el encabezado.
sudo apt update
sudo apt-get -y install nginx

sudo sed -i "40i\ \tadd_header X-Served-By '$HOSTNAME';" /etc/nginx/sites-enabled/default
sudo service nginx restart
