#!/usr/bin/env bash
#los primeros scripts deben ser para que los servidores sean identicos

sudo apt update
sudo apt-get -y install nginx

sudo sed -i "/listen 80 default_server/a add_header X-Served-By '$HOSTNAME';" /etc/nginx/sites-enabled/default
sudo service nginx restart
