#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get update && sudo apt-get upgrade
sudo apt-get -y install haproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}

echo  "
frontend haproxy-main
	bind *:80
	balance roundrobin 

backend nginx_webservers
	server 4373-web-01 54.226.169.216:80 check 
    server 4373-web-02 54.91.221.19:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart