#!/usr/bin/env bash
#print numbers from 1 to 20 / with conditions
#pos 4 , 9 , 17 - use CASE
i="0"
while [ $i -le 20 ]
do
	echo $i
	case $i in
		"4")
		  echo "bad luck from China"
		  ;;
		"9")
		  echo "bad luck from Japan"
		  ;;
		"17")
		  echo "bad luck from Italy"
		  ;;
	esac
	((i++))
done
