#!/usr/bin/env bash
#print 12 hours and 59 minutes
#hs 0 to 12 && minutes 1 to 59 [while]
hours=0
minutes=1

	echo "Hour: $((hours))"
while [ $hours -lt 12 ]
do
	while [ $minutes -lt 60 ]
		do
			echo $minutes
			((minutes++))
		done
	((hours++))
	echo "Hour: $((hours))"
	minutes=1
done

