#!/usr/bin/env bash
# Solucionar el servidor nginx corriendo como nginx (user)
# Libero el puerto 8080 para poder ocuparlo nuevamente
# netstat -nlp -> podemos identificar los puerto y ver a apache2 corriendo en el 8080
pkill apache2
#cambiamo el puerto al 8080
#cambio usuario www/data por nginx
chmod 700 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default

# confirmamos los cambios reiniciando el servidor
sudo -u nginx service nginx restart
