#!/usr/bin/env bash
# Solucionar el problema anterior en menos de 7 lineas
pkill apache2
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
